//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesabdari.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hesabdari_DBEntities : DbContext
    {
        public Hesabdari_DBEntities()
            : base("name=Hesabdari_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<AccountingTypes> AccountingTypes { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Login> Login { get; set; }
    }
}
